# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'SimpleDebts' do
  # Comment the next line if you don't want to use dynamic frameworks
  #  use_frameworks!

  pod 'Firebase/Core', '~> 4.2.0'
  pod 'Firebase/Messaging', '~> 4.2.0'
  
  pod 'FacebookSDK', '5.0.0'
  pod 'FacebookSDK/LoginKit', '5.0.0'
  pod 'FacebookSDK/ShareKit', '5.0.0'

  target 'SimpleDebtsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SimpleDebts-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleDebts-tvOS

  target 'SimpleDebts-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
