export const green = '#6EE0A1';
export const greenSecondary = '#C2EFD0';
export const red = '#FD8E96';
export const redSecondary = '#FDC4C8';
export const orange = '#FFD185';
export const black = 'rgb(52,63,75)'; // should be rgb(...)
export const gray = '#969FAA';
export const lightGray = '#ededed';
export const white = 'white';
